# coding: utf-8

"""
    PAYCOMET REST API

    PAYCOMET API REST for customers.  # noqa: E501

    OpenAPI spec version: 2.28.0
    Contact: tecnico@paycomet.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.inline_response20019_subscription import InlineResponse20019Subscription  # noqa: E501
from swagger_client.rest import ApiException


class TestInlineResponse20019Subscription(unittest.TestCase):
    """InlineResponse20019Subscription unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse20019Subscription(self):
        """Test InlineResponse20019Subscription"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.inline_response20019_subscription.InlineResponse20019Subscription()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
