# coding: utf-8

"""
    PAYCOMET REST API

    PAYCOMET API REST for customers.  # noqa: E501

    OpenAPI spec version: 2.28.0
    Contact: tecnico@paycomet.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.sepa_checkdocument_body import SepaCheckdocumentBody  # noqa: E501
from swagger_client.rest import ApiException


class TestSepaCheckdocumentBody(unittest.TestCase):
    """SepaCheckdocumentBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSepaCheckdocumentBody(self):
        """Test SepaCheckdocumentBody"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.sepa_checkdocument_body.SepaCheckdocumentBody()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
