# coding: utf-8

"""
    PAYCOMET REST API

    PAYCOMET API REST for customers.  # noqa: E501

    OpenAPI spec version: 2.28.0
    Contact: tecnico@paycomet.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.inline_response20014_payment import InlineResponse20014Payment  # noqa: E501
from swagger_client.rest import ApiException


class TestInlineResponse20014Payment(unittest.TestCase):
    """InlineResponse20014Payment unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse20014Payment(self):
        """Test InlineResponse20014Payment"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.inline_response20014_payment.InlineResponse20014Payment()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
