# coding: utf-8

"""
    PAYCOMET REST API

    PAYCOMET API REST for customers.  # noqa: E501

    OpenAPI spec version: 2.28.0
    Contact: tecnico@paycomet.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.sepa_api import SepaApi  # noqa: E501
from swagger_client.rest import ApiException


class TestSepaApi(unittest.TestCase):
    """SepaApi unit test stubs"""

    def setUp(self):
        self.api = SepaApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_document(self):
        """Test case for add_document

        Adds a SEPA document  # noqa: E501
        """
        pass

    def test_check_customer(self):
        """Test case for check_customer

        Check a customers SEPA documentation  # noqa: E501
        """
        pass

    def test_check_document(self):
        """Test case for check_document

        Check a SEPA document  # noqa: E501
        """
        pass

    def test_sepa_operations(self):
        """Test case for sepa_operations

        Send SEPA operations  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
