# coding: utf-8

"""
    PAYCOMET REST API

    PAYCOMET API REST for customers.  # noqa: E501

    OpenAPI spec version: 2.28.0
    Contact: tecnico@paycomet.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.v1form_payment_escrow_targets import V1formPaymentEscrowTargets  # noqa: E501
from swagger_client.rest import ApiException


class TestV1formPaymentEscrowTargets(unittest.TestCase):
    """V1formPaymentEscrowTargets unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV1formPaymentEscrowTargets(self):
        """Test V1formPaymentEscrowTargets"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.v1form_payment_escrow_targets.V1formPaymentEscrowTargets()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
