# coding: utf-8

"""
    PAYCOMET REST API

    PAYCOMET API REST for customers.  # noqa: E501

    OpenAPI spec version: 2.28.0
    Contact: tecnico@paycomet.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.v1subscriptionedit_payment import V1subscriptioneditPayment  # noqa: E501
from swagger_client.rest import ApiException


class TestV1subscriptioneditPayment(unittest.TestCase):
    """V1subscriptioneditPayment unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV1subscriptioneditPayment(self):
        """Test V1subscriptioneditPayment"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.v1subscriptionedit_payment.V1subscriptioneditPayment()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
