# coding: utf-8

"""
    PAYCOMET REST API

    PAYCOMET API REST for customers.  # noqa: E501

    OpenAPI spec version: 2.28.0
    Contact: tecnico@paycomet.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.inline_response20028_operations import InlineResponse20028Operations  # noqa: E501
from swagger_client.rest import ApiException


class TestInlineResponse20028Operations(unittest.TestCase):
    """InlineResponse20028Operations unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse20028Operations(self):
        """Test InlineResponse20028Operations"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.inline_response20028_operations.InlineResponse20028Operations()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
