# coding: utf-8

"""
    PAYCOMET REST API

    PAYCOMET API REST for customers.  # noqa: E501

    OpenAPI spec version: 2.28.0
    Contact: tecnico@paycomet.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.inline_response20024_submerchant import InlineResponse20024Submerchant  # noqa: E501
from swagger_client.rest import ApiException


class TestInlineResponse20024Submerchant(unittest.TestCase):
    """InlineResponse20024Submerchant unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse20024Submerchant(self):
        """Test InlineResponse20024Submerchant"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.inline_response20024_submerchant.InlineResponse20024Submerchant()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
